name:'Podcast Generator'
author: "Ray Villalobos"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branching:
  icon: "git-branch"
  color: "red"
inputs:
  emails:
    description: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}